### ISSUE TITLE
open file error

### ISSUE THREAD

**Issue by anthhub** [second-state/ssvm-nodejs-starter#16]
Following rust code will throw error, it look like this issue https://github.com/wasmerio/wasmer/issues/356

``` rust
   let mut input: Box<dyn std::io::Read> = match File::open(path) {
        Ok(f) => Box::new(f),
        Err(e) => {
            let mut estr = String::from(path);
            estr.push_str(": ");
            estr.push_str(&e.to_string());
            return Err(estr);
        }
    };
```

``` shell
 failed to find a pre-opened file descriptor through which "/workspaces/ssvm-nodejs-starter/2020-10-19-11-50-19.json" could be opened
```

**Comment by juntao** [comment]
To access file system through WASI, please follow this tutorial.

https://www.secondstate.io/articles/wasi-access-system-resources/

The issue here is that Rust compiler has not been updated to support WASI file system calls. So, you must add a manual workaround in Rust and wait for the official compiler release to catch up.

**Comment by anthhub** [comment]
Thank you! it works!
